# Generated by Django 3.1.7 on 2021-02-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_conversation', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('url_game', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('url_drawing', models.CharField(max_length=8, null=True)),
                ('order', models.PositiveIntegerField()),
                ('id_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETMApp.conversation')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnonyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ETMApp.message')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ETMApp.game')),
                ('id_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETMApp.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='id_userAnonyme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ETMApp.useranonyme'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='id_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETMApp.game'),
        ),
    ]
