# Generated by Django 3.1.7 on 2021-03-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranonyme',
            name='pseudo',
            field=models.CharField(max_length=50),
        ),
    ]
