# Generated by Django 3.2 on 2021-04-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMApp', '0005_auto_20210402_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='id_message',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
